version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: kafka-zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:latest
    container_name: kafka-kafka
    environment:
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9093
      - KAFKA_LISTENER_SECURITY_PROTOCOL=PLAINTEXT
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9093
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    ports:
      - "9093:9093"

  kafka-consumer:
    build: ./consumer
    container_name: kafka-consumer
    depends_on:
      - kafka
    environment:
      - KAFKA_BROKER=kafka:9093
      - KAFKA_TOPIC=my_topic

  kafka-producer:
    build: ./producer
    container_name: kafka-producer
    depends_on:
      - kafka
    environment:
      - KAFKA_BROKER=kafka:9093
      - KAFKA_TOPIC=my_topic
