version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    container_name: zookeeper
    ports:
      - "2181:2181"
  
  kafka:
    image: wurstmeister/kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT
      KAFKA_LISTENER_NAME_INSIDE: INSIDE
      KAFKA_LISTENER_PORT: 9093
      KAFKA_LISTENER_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_LISTENER_INTERNAL_HOST: kafka
      KAFKA_LISTENER_PORT_INTERNAL: 9093
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    ports:
      - "9093:9093"

  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf

  mqtt_to_kafka:
    build: ./mqtt_to_kafka
    container_name: mqtt_to_kafka
    depends_on:
      - kafka
      - mosquitto
    environment:
      MQTT_BROKER: mosquitto
      KAFKA_BROKER: kafka:9093
    volumes:
      - ./mqtt_to_kafka:/app
