apiVersion: v1
kind: ConfigMap
metadata:
  name: spark-config
  namespace: spark-cluster
data:
  spark-defaults.conf: |
    spark.master    spark://spark-master:7077
    spark.app.name  MySparkApp
    spark.executor.memory 4g
  spark-env.sh: |
    export SPARK_WORKER_CORES=2
    export SPARK_WORKER_MEMORY=4g
