apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-worker
  namespace: spark-cluster
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark-worker
  template:
    metadata:
      labels:
        app: spark-worker
    spec:
      containers:
        - name: spark-worker
          image: docker.io/bitnami/spark:latest
          imagePullPolicy: Always
          command:
            - "/opt/bitnami/spark/bin/spark-class"
          args:
            - "org.apache.spark.deploy.worker.Worker"
            - "spark://spark-master:7077"  # Change this to your Spark master URL
          env:
            - name: SPARK_MODE
              value: "worker"
            - name: SPARK_MASTER_URL
              value: "spark://spark-master:7077"
          ports:
            - containerPort: 8081
          volumeMounts:
            - name: spark-data
              mountPath: /data/spark
      volumes:
        - name: spark-data
          persistentVolumeClaim:
            claimName: spark-pvc
